# Generated by Django 6.1.1 on 2026-09-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0002_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
    ]
