# Generated by Django 6.1.1 on 2026-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Lacteos', 'Lacteos'), ('Bebidas', 'Bebidas'), ('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Enlatados', 'Enlatados'), ('Dulces', 'Dulces'), ('Embutidos', 'Embutidos'), ('Granos', 'Granos'), ('Legumbres', 'Legumbres'), ('', '')], default='Lacteos', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Kg', 'Kilogramos (kg)'), ('Litros', 'Litros (L)'), ('Gramos', 'Gramos (g)')], default='Kg', max_length=20),
        ),
    ]
