# Generated by Django 6.1.1 on 2026-09-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_categoria_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Lacteos', 'Lacteos'), ('Bebidas', 'Bebidas'), ('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Enlatados', 'Enlatados'), ('Dulces', 'Dulces'), ('Embutidos', 'Embutidos'), ('Granos', 'Granos'), ('Legumbres', 'Legumbres')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Kg', 'Kilogramos (kg)'), ('Litros', 'Litros (L)'), ('Gramos', 'Gramos (g)')], default='', max_length=20),
        ),
    ]
