# Generated by Django 6.1.1 on 2026-09-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Kg', 'Kilogramos (kg)'), ('Litros', 'Litros (L)'), ('Gramos', 'Gramos (g)'), ('Mililitros', 'Mililitros (ml)')], default='', max_length=20),
        ),
    ]
