# Generated by Django 6.1.1 on 2026-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Lacteos', 'Lacteos'), ('Bebidas', 'Bebidas'), ('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Enlatados', 'Enlatados'), ('Dulces', 'Dulces'), ('Embutidos', 'Embutidos'), ('Granos', 'Granos'), ('Legumbres', 'Legumbres'), ('Paqueteria', 'Paqueteria')], default='', max_length=50),
        ),
    ]
